### ISSUE TITLE
Expo 37 compatibility

### ISSUE THREAD

**Issue by robert-johansson** [louiechristie/mood-check-in#14]
This seems like a nice app to try out Expo + react native paper. Is there any chance you could update it to work with Expo 37? The Expo iOS app currently requires Expo >= 35 to be used in the project.

**Comment by louiechristie** [comment]
Hi @robert-johansson thanks for reaching out!

This is an old app.
- I could maybe upgrade it.
- Or, I might have newer, better, code I could share.
- Or, I might do a tutorial on Expo + react native paper that would be better for your needs.

How did you find this code, and why?

What do you need?

**Comment by robert-johansson** [comment]
Hi @louiechristie - thanks a lot for your answer. I searched GitHub for projects using Expo + react native paper. 

I'm especially interested in apps that are a bit larger than a typical very small boilerplate app. Therefore I was interested in seeing your app in action.

I'm interested in all your options - of course it would be very nice with a tutorial, if you have the time and are willing to do such work. It would also be great to see examples that run with newer Expo, especially if the projects are somewhat complete.

Thank you very much,
Robert

**Comment by louiechristie** [comment]
@robert-johansson 

For the most complete example of a React Native paper with Expo app, check this out:
https://expo.io/@louiechristie/react-native-paper-example

I built it myself from the React Native Paper [example app code](https://github.com/callstack/react-native-paper/tree/master/example) by  [@callstack](https://github.com/callstack) - because in my experience the [snack example](https://snack.expo.io/@react-native-paper/github.com-callstack-react-native-paper:example) they link to from the documentation is [often ](https://www.google.com/search?q=snack+react+native+paper+issue) broken, [as it is now](https://github.com/callstack/react-native-paper/issues/2234).

To build this on your computer, open a terminal and do these commands:

```console
git clone git@github.com:callstack/react-native-paper.git
yarn bootstrap
yarn example start
```

@robert-johansson, does this meet your needs?

**Comment by robert-johansson** [comment]
@louiechristie This is great - thank you! And thank you for bringing this issue up with the React Native Paper developers. Looking forward to diving into this example.

**Comment by louiechristie** [comment]
@robert-johansson App upgraded to Expo v38 in e91151c	

Closing this issue.

**Comment by louiechristie** [comment]
Added react native web paper example:
https://react-native-web-paper-example.netlify.app/

To help this newbie question about building a website MVP (minimum viable product) without learning CSS coding:
https://news.ycombinator.com/item?id=28500816
